language: python

python:
    - "3.9"

before_install:
    - sudo pip install virtualenv
    - virtualenv $TRAVIS_BUILD_DIR/arteria-bclconvert/

install:
    - source $TRAVIS_BUILD_DIR/arteria-bclconvert/bin/activate
    - pip install -e . -r ./requirements/dev

script:
    - nosetests tests/

notifications:
    email: false
