
# This is a basic workflow to help you get started with Actions

name: Workflow integration

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches:
     - main
     - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dry_run: # health check job for testing and code formatting check
    name: test service
    runs-on: ubuntu-22.04 # os for running the job
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: create output runfolders
        run: mkdir -p test/fastq test/logs
      - name: start docker container
        run: >
          VERSION=${GITHUB_REF##*/} docker-compose -f docker-compose-test.yaml up -d
        working-directory: docker
      - name: sleep 5
        run: sleep 5
      - name: start processing
        run: >
          curl -X POST --data '{"additional_args": ""}' http://127.0.0.1:10900/api/1.0/start/runfolder1
      - name: check status
        run: >
          curl http://127.0.0.1:10900/api/1.0/status/1
      - name: sleep
        run: sleep 20
      - name: check status
        run: >
          curl http://127.0.0.1:10900/api/1.0/status/1
      - name: check that status is done
        run: >
          curl http://127.0.0.1:10900/api/1.0/status/1 | python -c 'import sys; import json; exit(0) if (json.loads(sys.stdin.read()))["state"] == "done" else exit(1)'
